# Generated by Django 6.0 on 2026-02-03 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9]{7,15}$", "Enter a valid phone number"
                    )
                ],
            ),
        ),
    ]
