from django.db import models


class UserRole(models.TextChoices):
    USER = "USER", "User"
    ADMIN = "ADMIN", "Admin"


class AccountStatus(models.TextChoices):
    ACTIVE = "ACTIVE", "Active"
    SUSPENDED = "SUSPENDED", "Suspended"
    DELETED = "DELETED", "Deleted"


class Language(models.TextChoices):
    EN = "en", "English"
    ES = "es", "Spanish"
    FR = "fr", "French"
    DE = "de", "German"
    IT = "it", "Italian"
    PT = "pt", "Portuguese"
    RU = "ru", "Russian"
    ZH = "zh", "Chinese"
    JA = "ja", "Japanese"
    KO = "ko", "Korean"
    AR = "ar", "Arabic"
    HI = "hi", "Hindi"
    NL = "nl", "Dutch"
    SV = "sv", "Swedish"
    PL = "pl", "Polish"


class Currency(models.TextChoices):
    USD = "USD", "US Dollar"
    EUR = "EUR", "Euro"
    GBP = "GBP", "British Pound"
    JPY = "JPY", "Japanese Yen"
    CNY = "CNY", "Chinese Yuan"
    INR = "INR", "Indian Rupee"
    AUD = "AUD", "Australian Dollar"
    CAD = "CAD", "Canadian Dollar"
    CHF = "CHF", "Swiss Franc"
    SEK = "SEK", "Swedish Krona"
    NZD = "NZD", "New Zealand Dollar"
    MXN = "MXN", "Mexican Peso"
    SGD = "SGD", "Singapore Dollar"
    HKD = "HKD", "Hong Kong Dollar"
    NOK = "NOK", "Norwegian Krone"
    KRW = "KRW", "South Korean Won"
    TRY = "TRY", "Turkish Lira"
    RUB = "RUB", "Russian Ruble"
    BRL = "BRL", "Brazilian Real"
    ZAR = "ZAR", "South African Rand"


class Country(models.TextChoices):
    # Europe
    AT = "AT", "Austria"
    BY = "BY", "Belarus"
    BE = "BE", "Belgium"
    BG = "BG", "Bulgaria"
    HR = "HR", "Croatia"
    CY = "CY", "Cyprus"
    CZ = "CZ", "Czech Republic"
    DK = "DK", "Denmark"
    EE = "EE", "Estonia"
    FI = "FI", "Finland"
    FR = "FR", "France"
    DE = "DE", "Germany"
    GR = "GR", "Greece"
    HU = "HU", "Hungary"
    IE = "IE", "Ireland"
    IT = "IT", "Italy"
    LV = "LV", "Latvia"
    LT = "LT", "Lithuania"
    LU = "LU", "Luxembourg"
    MT = "MT", "Malta"
    MD = "MD", "Moldova"
    NL = "NL", "Netherlands"
    NO = "NO", "Norway"
    PL = "PL", "Poland"
    PT = "PT", "Portugal"
    RO = "RO", "Romania"
    RU = "RU", "Russia"
    RS = "RS", "Serbia"
    SK = "SK", "Slovakia"
    SI = "SI", "Slovenia"
    ES = "ES", "Spain"
    SE = "SE", "Sweden"
    CH = "CH", "Switzerland"
    UA = "UA", "Ukraine"
    GB = "GB", "United Kingdom"

    # Americas - North America
    US = "US", "United States"
    CA = "CA", "Canada"
    MX = "MX", "Mexico"

    # Americas - Central America & Caribbean
    BZ = "BZ", "Belize"
    CR = "CR", "Costa Rica"
    SV = "SV", "El Salvador"
    GT = "GT", "Guatemala"
    HN = "HN", "Honduras"
    NI = "NI", "Nicaragua"
    PA = "PA", "Panama"
    AG = "AG", "Antigua and Barbuda"
    BS = "BS", "Bahamas"
    BB = "BB", "Barbados"
    CU = "CU", "Cuba"
    DM = "DM", "Dominica"
    DO = "DO", "Dominican Republic"
    GD = "GD", "Grenada"
    HT = "HT", "Haiti"
    JM = "JM", "Jamaica"
    KN = "KN", "Saint Kitts and Nevis"
    LC = "LC", "Saint Lucia"
    VC = "VC", "Saint Vincent and the Grenadines"
    TT = "TT", "Trinidad and Tobago"

    # Americas - South America
    AR = "AR", "Argentina"
    BO = "BO", "Bolivia"
    BR = "BR", "Brazil"
    CL = "CL", "Chile"
    CO = "CO", "Colombia"
    EC = "EC", "Ecuador"
    GY = "GY", "Guyana"
    PE = "PE", "Peru"
    PY = "PY", "Paraguay"
    SR = "SR", "Suriname"
    UY = "UY", "Uruguay"
    VE = "VE", "Venezuela"

    # Asia - East Asia
    CN = "CN", "China"
    HK = "HK", "Hong Kong"
    JP = "JP", "Japan"
    KP = "KP", "North Korea"
    KR = "KR", "South Korea"
    MO = "MO", "Macau"
    MN = "MN", "Mongolia"
    TW = "TW", "Taiwan"

    # Asia - Southeast Asia
    BN = "BN", "Brunei"
    KH = "KH", "Cambodia"
    ID = "ID", "Indonesia"
    LA = "LA", "Laos"
    MY = "MY", "Malaysia"
    MM = "MM", "Myanmar"
    PH = "PH", "Philippines"
    SG = "SG", "Singapore"
    TH = "TH", "Thailand"
    TL = "TL", "Timor-Leste"
    VN = "VN", "Vietnam"

    # Asia - South Asia
    AF = "AF", "Afghanistan"
    BD = "BD", "Bangladesh"
    BT = "BT", "Bhutan"
    IN = "IN", "India"
    NP = "NP", "Nepal"
    PK = "PK", "Pakistan"
    LK = "LK", "Sri Lanka"

    # Asia - Central Asia
    KZ = "KZ", "Kazakhstan"
    KG = "KG", "Kyrgyzstan"
    TJ = "TJ", "Tajikistan"
    TM = "TM", "Turkmenistan"
    UZ = "UZ", "Uzbekistan"

    # Asia - West Asia & Middle East
    AE = "AE", "United Arab Emirates"
    BH = "BH", "Bahrain"
    IQ = "IQ", "Iraq"
    IR = "IR", "Iran"
    IL = "IL", "Israel"
    JO = "JO", "Jordan"
    KW = "KW", "Kuwait"
    LB = "LB", "Lebanon"
    OM = "OM", "Oman"
    QA = "QA", "Qatar"
    SA = "SA", "Saudi Arabia"
    SY = "SY", "Syria"
    TR = "TR", "Turkey"
    YE = "YE", "Yemen"

    # Africa - North Africa
    DZ = "DZ", "Algeria"
    EG = "EG", "Egypt"
    LY = "LY", "Libya"
    MA = "MA", "Morocco"
    SD = "SD", "Sudan"
    TN = "TN", "Tunisia"

    # Africa - West Africa
    BJ = "BJ", "Benin"
    BF = "BF", "Burkina Faso"
    CV = "CV", "Cape Verde"
    CI = "CI", "Côte d'Ivoire"
    GM = "GM", "Gambia"
    GH = "GH", "Ghana"
    GN = "GN", "Guinea"
    GW = "GW", "Guinea-Bissau"
    LR = "LR", "Liberia"
    ML = "ML", "Mali"
    MR = "MR", "Mauritania"
    NE = "NE", "Niger"
    NG = "NG", "Nigeria"
    SN = "SN", "Senegal"
    SL = "SL", "Sierra Leone"
    TG = "TG", "Togo"

    # Africa - Central Africa
    AO = "AO", "Angola"
    CM = "CM", "Cameroon"
    CF = "CF", "Central African Republic"
    TD = "TD", "Chad"
    CG = "CG", "Congo"
    CD = "CD", "Democratic Republic of the Congo"
    GQ = "GQ", "Equatorial Guinea"
    GA = "GA", "Gabon"
    ST = "ST", "São Tomé and Príncipe"

    # Africa - East Africa
    BI = "BI", "Burundi"
    KM = "KM", "Comoros"
    DJ = "DJ", "Djibouti"
    ER = "ER", "Eritrea"
    ET = "ET", "Ethiopia"
    KE = "KE", "Kenya"
    MG = "MG", "Madagascar"
    MW = "MW", "Malawi"
    MU = "MU", "Mauritius"
    MZ = "MZ", "Mozambique"
    RW = "RW", "Rwanda"
    SC = "SC", "Seychelles"
    SO = "SO", "Somalia"
    SS = "SS", "South Sudan"
    TZ = "TZ", "Tanzania"
    UG = "UG", "Uganda"
    ZM = "ZM", "Zambia"
    ZW = "ZW", "Zimbabwe"

    # Africa - Southern Africa
    BW = "BW", "Botswana"
    LS = "LS", "Lesotho"
    NA = "NA", "Namibia"
    ZA = "ZA", "South Africa"

    # Oceania
    AU = "AU", "Australia"
    FJ = "FJ", "Fiji"
    KI = "KI", "Kiribati"
    MH = "MH", "Marshall Islands"
    FM = "FM", "Micronesia"
    NR = "NR", "Nauru"
    NZ = "NZ", "New Zealand"
    PW = "PW", "Palau"
    PG = "PG", "Papua New Guinea"
    WS = "WS", "Samoa"
    SB = "SB", "Solomon Islands"
    TO = "TO", "Tonga"
    TV = "TV", "Tuvalu"
    VU = "VU", "Vanuatu"
